### PR TITLE
Updated HelioHost Wiki

### PR DESCRIPTION
**Pull request by chippytech**
- Replaced "Google Apps" with "Google Workspace"
- Replaced "softaculous" with "Plesk Applications Installer"
- Replaced "free .tk domain \(which you can register at [dot.tk](http://dot.tk/)\)\*" with "free domain \(which you can register at [Freenom](https://www.freenom.com/)\)\*"
- Updated AutoInstaller "Through Plesk, you can use their auto-installer to install popular software \(such as blogging and forum platforms\) to your website, but you are responsible for ALL maintenance, design, etc."
- Replaced Java/JSP with Python

### CODE REVIEW

**Comment by ABUCKY0** [comment]
Freenom is dead

**Comment by ABUCKY0** [comment]
And why would you replace Java/JSP with Python?

**Comment by MoneyBrozYT** [comment]
Instead of putting freenom, you should have put free heliohost.us or helioho.st subdomain instead.

**Review by Kryd0s — CHANGES_REQUESTED** [review]
What we mean by "dangerous" is languages that use a massive amount of system resources or tend to cause instability or drops in uptime. Python, unless you're intentionally trying to crash the server, is actually a really "safe" language. It doesn't use excessive amounts of memory normally, and doesn't generally use a lot of CPU either. Honestly, I would say that PHP is more dangerous than Python. Unless you have a phobia of snakes...

We do intend to install Java/JSP on our servers again so we're not going to change that. Furthermore, Python is available on ALL of our servers, so specifying that it is only on Johnny is also wrong in that regard.

Revert johnny.md to its original state.

**Pull request merged**
