### PR TITLE
Modification of Contributing to Wiki and added information into Server Pages

### PR DESCRIPTION
**Pull request by vincentmaule**
Hello Helio Networks,

Below are changes from a high level:
- Provided more detail on the steps to follow with contributing to Helio Networks through Gitbooks.
- Provided more detail on some of the servers used by Helio Networks/Helio Host.
  - Added links to each individual server to Monitoring Service.
  - Provide "Realistic Uptime Goal" to servers where applicable.
  - Added Tags to servers where applicable.

Please let me know if anything needs to be changed.

Kind Regards,
Vince

### CODE REVIEW

**Review by Kryd0s — CHANGES_REQUESTED** [review]
The VPS that is being monitored is actually on Annie right now, not Sparkie.

**Comment by vincentmaule** [comment]
Hello Kryd0s,

Thank you for pointing this out!

> The VPS that is being monitored is actually on Annie right now, not Sparkie.

I have made the changes to reflect this comment.
It was a good thing to as I did find two links using `www` within them & have modified those.

Please let me know if there are any other changes I need to make.
Kind Regards,
Vince

**Review by Kryd0s — CHANGES_REQUESTED** [review]
Remove the `&#x20;` on the contributing page.

**Comment by vincentmaule** [comment]
Thanks for finding that;
- I have removed the `space`/`&#x20;` as mentioned in the contributing page.
- I have modified an & -> and as that is a force of habit for personal documentation.
- Re-reviewed all other files that could be a cause for holding this PR.

Please let me know if there are any other changes I need to make.
Kind Regards,
Vince

**Review by Kryd0s — CHANGES_REQUESTED** [review]
Why did you change the title from "Table of Contents" to "Table of contents" with a lowercase c? Here is a guide for capitalization of titles https://www.grammarly.com/blog/capitalization-in-the-titles/ The rules are fairly complicated, I agree, but nouns should definitely remain capitalized.

**Comment by vincentmaule** [comment]
Hello Kryd0s & HelioNetworks,

It seems as though this Pull Request runs in direct conflict with the contribution guidelines as listed in the [Code Style](https://github.com/HelioNetworks/wiki/blob/master/misc/code-style.md) (Missed this before as this must be page that will only be shown through Git Repo & not live in the Wiki) Page.

As such, I will `Close with Comment` since this Pull Request does not meet the spirit of the requirements.

Kind Regards,
Vince

**Pull request closed without merging**
