### PR TITLE
Remove Invalid Edits from chippytech's PR (#28)

### PR DESCRIPTION
**Pull request by ABUCKY0**

### CODE REVIEW

**Comment by ABUCKY0** [comment]
link with #28

**Comment by MoneyBrozYT** [comment]
johnny.md still has Python replaced by Java/JSP from chippytechs PR.

**Comment by ABUCKY0** [comment]
If you look at the files changed it doesn't. Idk how to remove a commit so I just undid what he did by putting Java/JSP in place of Python

**Comment by MoneyBrozYT** [comment]
Yeah i misread that.

**Comment by Kryd0s** [comment]
Thanks for fixing ChippyTech's PR.

**Pull request merged**
